name: Deploy to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            mkdir -p /home/ec2-user/app
            cd /home/ec2-user/app

            if [ ! -d ".git" ]; then
              git clone https://github.com/thejusr28/my-devops-app.git .
            else
              git pull origin main
            fi

            docker stop my-app1 || true
            docker rm my-app1 || true

            docker build -t my-devops-app .

            docker run -d -p 80:80 --name my-app1 my-devops-app

            docker system prune -af || true
